spring.application.name=restaurante-pedido
server.port=8081

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql

# JWT — chave pública do serviço usuario-autenticacao para validar tokens
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/publicKey.pem
