quarkus.application.name=fiap-restaurante
quarkus.smallrye-graphql.ui.always-include=true
quarkus.native.resources.includes=keys/*.pem

# GraphQL: expoe mensagens de exceções de negócio para os clientes
mp.graphql.nonFatalExceptionClasses=br.com.fiaprestaurante.shared.domain.exception.BusinessException

smallrye.jwt.sign.key.location=keys/privateKey.pem
mp.jwt.verify.publickey.location=keys/publicKey.pem
mp.jwt.verify.issuer=fiap-restaurante
smallrye.jwt.new-token.issuer=fiap-restaurante
smallrye.jwt.new-token.lifespan=3600

# gRPC server
quarkus.grpc.server.port=9000
quarkus.grpc.server.enable-reflection-service=true

%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:fiaprestaurante-dev;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:fiaprestaurante-test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.grpc.server.port=0

%prod.quarkus.datasource.db-kind=mysql
%prod.quarkus.datasource.username=${DB_USERNAME:fiap}
%prod.quarkus.datasource.password=${DB_PASSWORD:fiap}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/fiap_restaurante}
%prod.quarkus.hibernate-orm.schema-management.strategy=update
