// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 3.25.5
package br.com.fiaprestaurante.grpc;

public interface BuscarUsuarioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fiaprestaurante.BuscarUsuarioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string publicId = 1;</code>
   * @return The publicId.
   */
  java.lang.String getPublicId();
  /**
   * <code>string publicId = 1;</code>
   * @return The bytes for publicId.
   */
  com.google.protobuf.ByteString
      getPublicIdBytes();
}
