// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 3.25.5
package br.com.fiaprestaurante.grpc;

public final class UsuarioProto {
  private UsuarioProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fiaprestaurante_BuscarUsuarioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fiaprestaurante_BuscarUsuarioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fiaprestaurante_UsuarioResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fiaprestaurante_UsuarioResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fiaprestaurante_VerificarPerfilRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fiaprestaurante_VerificarPerfilRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fiaprestaurante_VerificarPerfilResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fiaprestaurante_VerificarPerfilResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rusuario.proto\022\017fiaprestaurante\"(\n\024Busc" +
      "arUsuarioRequest\022\020\n\010publicId\030\001 \001(\t\"P\n\017Us" +
      "uarioResponse\022\020\n\010publicId\030\001 \001(\t\022\014\n\004nome\030" +
      "\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\016\n\006perfil\030\004 \001(\t\"C\n\026" +
      "VerificarPerfilRequest\022\020\n\010publicId\030\001 \001(\t" +
      "\022\027\n\017perfilRequerido\030\002 \001(\t\"-\n\027VerificarPe" +
      "rfilResponse\022\022\n\nautorizado\030\001 \001(\0102\320\001\n\016Usu" +
      "arioService\022X\n\rBuscarUsuario\022%.fiapresta" +
      "urante.BuscarUsuarioRequest\032 .fiaprestau" +
      "rante.UsuarioResponse\022d\n\017VerificarPerfil" +
      "\022\'.fiaprestaurante.VerificarPerfilReques" +
      "t\032(.fiaprestaurante.VerificarPerfilRespo" +
      "nseB-\n\033br.com.fiaprestaurante.grpcB\014Usua" +
      "rioProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fiaprestaurante_BuscarUsuarioRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fiaprestaurante_BuscarUsuarioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fiaprestaurante_BuscarUsuarioRequest_descriptor,
        new java.lang.String[] { "PublicId", });
    internal_static_fiaprestaurante_UsuarioResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fiaprestaurante_UsuarioResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fiaprestaurante_UsuarioResponse_descriptor,
        new java.lang.String[] { "PublicId", "Nome", "Email", "Perfil", });
    internal_static_fiaprestaurante_VerificarPerfilRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fiaprestaurante_VerificarPerfilRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fiaprestaurante_VerificarPerfilRequest_descriptor,
        new java.lang.String[] { "PublicId", "PerfilRequerido", });
    internal_static_fiaprestaurante_VerificarPerfilResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_fiaprestaurante_VerificarPerfilResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fiaprestaurante_VerificarPerfilResponse_descriptor,
        new java.lang.String[] { "Autorizado", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
