// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 3.25.5
package br.com.fiaprestaurante.grpc;

public interface UsuarioResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fiaprestaurante.UsuarioResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string publicId = 1;</code>
   * @return The publicId.
   */
  java.lang.String getPublicId();
  /**
   * <code>string publicId = 1;</code>
   * @return The bytes for publicId.
   */
  com.google.protobuf.ByteString
      getPublicIdBytes();

  /**
   * <code>string nome = 2;</code>
   * @return The nome.
   */
  java.lang.String getNome();
  /**
   * <code>string nome = 2;</code>
   * @return The bytes for nome.
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string perfil = 4;</code>
   * @return The perfil.
   */
  java.lang.String getPerfil();
  /**
   * <code>string perfil = 4;</code>
   * @return The bytes for perfil.
   */
  com.google.protobuf.ByteString
      getPerfilBytes();
}
