// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 3.25.5
package br.com.fiaprestaurante.grpc;

public interface VerificarPerfilResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fiaprestaurante.VerificarPerfilResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool autorizado = 1;</code>
   * @return The autorizado.
   */
  boolean getAutorizado();
}
