// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 3.25.5
package br.com.fiaprestaurante.grpc;

/**
 * Protobuf type {@code fiaprestaurante.VerificarPerfilResponse}
 */
public final class VerificarPerfilResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fiaprestaurante.VerificarPerfilResponse)
    VerificarPerfilResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerificarPerfilResponse.newBuilder() to construct.
  private VerificarPerfilResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerificarPerfilResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VerificarPerfilResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.fiaprestaurante.grpc.VerificarPerfilResponse.class, br.com.fiaprestaurante.grpc.VerificarPerfilResponse.Builder.class);
  }

  public static final int AUTORIZADO_FIELD_NUMBER = 1;
  private boolean autorizado_ = false;
  /**
   * <code>bool autorizado = 1;</code>
   * @return The autorizado.
   */
  @java.lang.Override
  public boolean getAutorizado() {
    return autorizado_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (autorizado_ != false) {
      output.writeBool(1, autorizado_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (autorizado_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, autorizado_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.fiaprestaurante.grpc.VerificarPerfilResponse)) {
      return super.equals(obj);
    }
    br.com.fiaprestaurante.grpc.VerificarPerfilResponse other = (br.com.fiaprestaurante.grpc.VerificarPerfilResponse) obj;

    if (getAutorizado()
        != other.getAutorizado()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUTORIZADO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAutorizado());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.fiaprestaurante.grpc.VerificarPerfilResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fiaprestaurante.VerificarPerfilResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fiaprestaurante.VerificarPerfilResponse)
      br.com.fiaprestaurante.grpc.VerificarPerfilResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.fiaprestaurante.grpc.VerificarPerfilResponse.class, br.com.fiaprestaurante.grpc.VerificarPerfilResponse.Builder.class);
    }

    // Construct using br.com.fiaprestaurante.grpc.VerificarPerfilResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      autorizado_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilResponse_descriptor;
    }

    @java.lang.Override
    public br.com.fiaprestaurante.grpc.VerificarPerfilResponse getDefaultInstanceForType() {
      return br.com.fiaprestaurante.grpc.VerificarPerfilResponse.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.fiaprestaurante.grpc.VerificarPerfilResponse build() {
      br.com.fiaprestaurante.grpc.VerificarPerfilResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.fiaprestaurante.grpc.VerificarPerfilResponse buildPartial() {
      br.com.fiaprestaurante.grpc.VerificarPerfilResponse result = new br.com.fiaprestaurante.grpc.VerificarPerfilResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.com.fiaprestaurante.grpc.VerificarPerfilResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.autorizado_ = autorizado_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.fiaprestaurante.grpc.VerificarPerfilResponse) {
        return mergeFrom((br.com.fiaprestaurante.grpc.VerificarPerfilResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.fiaprestaurante.grpc.VerificarPerfilResponse other) {
      if (other == br.com.fiaprestaurante.grpc.VerificarPerfilResponse.getDefaultInstance()) return this;
      if (other.getAutorizado() != false) {
        setAutorizado(other.getAutorizado());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              autorizado_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean autorizado_ ;
    /**
     * <code>bool autorizado = 1;</code>
     * @return The autorizado.
     */
    @java.lang.Override
    public boolean getAutorizado() {
      return autorizado_;
    }
    /**
     * <code>bool autorizado = 1;</code>
     * @param value The autorizado to set.
     * @return This builder for chaining.
     */
    public Builder setAutorizado(boolean value) {

      autorizado_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool autorizado = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutorizado() {
      bitField0_ = (bitField0_ & ~0x00000001);
      autorizado_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fiaprestaurante.VerificarPerfilResponse)
  }

  // @@protoc_insertion_point(class_scope:fiaprestaurante.VerificarPerfilResponse)
  private static final br.com.fiaprestaurante.grpc.VerificarPerfilResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.fiaprestaurante.grpc.VerificarPerfilResponse();
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerificarPerfilResponse>
      PARSER = new com.google.protobuf.AbstractParser<VerificarPerfilResponse>() {
    @java.lang.Override
    public VerificarPerfilResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VerificarPerfilResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerificarPerfilResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.fiaprestaurante.grpc.VerificarPerfilResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

