// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 3.25.5
package br.com.fiaprestaurante.grpc;

/**
 * Protobuf type {@code fiaprestaurante.VerificarPerfilRequest}
 */
public final class VerificarPerfilRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fiaprestaurante.VerificarPerfilRequest)
    VerificarPerfilRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerificarPerfilRequest.newBuilder() to construct.
  private VerificarPerfilRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerificarPerfilRequest() {
    publicId_ = "";
    perfilRequerido_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VerificarPerfilRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.fiaprestaurante.grpc.VerificarPerfilRequest.class, br.com.fiaprestaurante.grpc.VerificarPerfilRequest.Builder.class);
  }

  public static final int PUBLICID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object publicId_ = "";
  /**
   * <code>string publicId = 1;</code>
   * @return The publicId.
   */
  @java.lang.Override
  public java.lang.String getPublicId() {
    java.lang.Object ref = publicId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      publicId_ = s;
      return s;
    }
  }
  /**
   * <code>string publicId = 1;</code>
   * @return The bytes for publicId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPublicIdBytes() {
    java.lang.Object ref = publicId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      publicId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERFILREQUERIDO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object perfilRequerido_ = "";
  /**
   * <code>string perfilRequerido = 2;</code>
   * @return The perfilRequerido.
   */
  @java.lang.Override
  public java.lang.String getPerfilRequerido() {
    java.lang.Object ref = perfilRequerido_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      perfilRequerido_ = s;
      return s;
    }
  }
  /**
   * <code>string perfilRequerido = 2;</code>
   * @return The bytes for perfilRequerido.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPerfilRequeridoBytes() {
    java.lang.Object ref = perfilRequerido_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      perfilRequerido_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publicId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, publicId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(perfilRequerido_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, perfilRequerido_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(publicId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, publicId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(perfilRequerido_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, perfilRequerido_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.fiaprestaurante.grpc.VerificarPerfilRequest)) {
      return super.equals(obj);
    }
    br.com.fiaprestaurante.grpc.VerificarPerfilRequest other = (br.com.fiaprestaurante.grpc.VerificarPerfilRequest) obj;

    if (!getPublicId()
        .equals(other.getPublicId())) return false;
    if (!getPerfilRequerido()
        .equals(other.getPerfilRequerido())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PUBLICID_FIELD_NUMBER;
    hash = (53 * hash) + getPublicId().hashCode();
    hash = (37 * hash) + PERFILREQUERIDO_FIELD_NUMBER;
    hash = (53 * hash) + getPerfilRequerido().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.fiaprestaurante.grpc.VerificarPerfilRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fiaprestaurante.VerificarPerfilRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fiaprestaurante.VerificarPerfilRequest)
      br.com.fiaprestaurante.grpc.VerificarPerfilRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.fiaprestaurante.grpc.VerificarPerfilRequest.class, br.com.fiaprestaurante.grpc.VerificarPerfilRequest.Builder.class);
    }

    // Construct using br.com.fiaprestaurante.grpc.VerificarPerfilRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      publicId_ = "";
      perfilRequerido_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.fiaprestaurante.grpc.UsuarioProto.internal_static_fiaprestaurante_VerificarPerfilRequest_descriptor;
    }

    @java.lang.Override
    public br.com.fiaprestaurante.grpc.VerificarPerfilRequest getDefaultInstanceForType() {
      return br.com.fiaprestaurante.grpc.VerificarPerfilRequest.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.fiaprestaurante.grpc.VerificarPerfilRequest build() {
      br.com.fiaprestaurante.grpc.VerificarPerfilRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.fiaprestaurante.grpc.VerificarPerfilRequest buildPartial() {
      br.com.fiaprestaurante.grpc.VerificarPerfilRequest result = new br.com.fiaprestaurante.grpc.VerificarPerfilRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.com.fiaprestaurante.grpc.VerificarPerfilRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.publicId_ = publicId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.perfilRequerido_ = perfilRequerido_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.fiaprestaurante.grpc.VerificarPerfilRequest) {
        return mergeFrom((br.com.fiaprestaurante.grpc.VerificarPerfilRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.fiaprestaurante.grpc.VerificarPerfilRequest other) {
      if (other == br.com.fiaprestaurante.grpc.VerificarPerfilRequest.getDefaultInstance()) return this;
      if (!other.getPublicId().isEmpty()) {
        publicId_ = other.publicId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPerfilRequerido().isEmpty()) {
        perfilRequerido_ = other.perfilRequerido_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              publicId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              perfilRequerido_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object publicId_ = "";
    /**
     * <code>string publicId = 1;</code>
     * @return The publicId.
     */
    public java.lang.String getPublicId() {
      java.lang.Object ref = publicId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publicId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string publicId = 1;</code>
     * @return The bytes for publicId.
     */
    public com.google.protobuf.ByteString
        getPublicIdBytes() {
      java.lang.Object ref = publicId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string publicId = 1;</code>
     * @param value The publicId to set.
     * @return This builder for chaining.
     */
    public Builder setPublicId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      publicId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string publicId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicId() {
      publicId_ = getDefaultInstance().getPublicId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string publicId = 1;</code>
     * @param value The bytes for publicId to set.
     * @return This builder for chaining.
     */
    public Builder setPublicIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      publicId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object perfilRequerido_ = "";
    /**
     * <code>string perfilRequerido = 2;</code>
     * @return The perfilRequerido.
     */
    public java.lang.String getPerfilRequerido() {
      java.lang.Object ref = perfilRequerido_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        perfilRequerido_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string perfilRequerido = 2;</code>
     * @return The bytes for perfilRequerido.
     */
    public com.google.protobuf.ByteString
        getPerfilRequeridoBytes() {
      java.lang.Object ref = perfilRequerido_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        perfilRequerido_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string perfilRequerido = 2;</code>
     * @param value The perfilRequerido to set.
     * @return This builder for chaining.
     */
    public Builder setPerfilRequerido(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      perfilRequerido_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string perfilRequerido = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPerfilRequerido() {
      perfilRequerido_ = getDefaultInstance().getPerfilRequerido();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string perfilRequerido = 2;</code>
     * @param value The bytes for perfilRequerido to set.
     * @return This builder for chaining.
     */
    public Builder setPerfilRequeridoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      perfilRequerido_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fiaprestaurante.VerificarPerfilRequest)
  }

  // @@protoc_insertion_point(class_scope:fiaprestaurante.VerificarPerfilRequest)
  private static final br.com.fiaprestaurante.grpc.VerificarPerfilRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.fiaprestaurante.grpc.VerificarPerfilRequest();
  }

  public static br.com.fiaprestaurante.grpc.VerificarPerfilRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerificarPerfilRequest>
      PARSER = new com.google.protobuf.AbstractParser<VerificarPerfilRequest>() {
    @java.lang.Override
    public VerificarPerfilRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VerificarPerfilRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerificarPerfilRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.fiaprestaurante.grpc.VerificarPerfilRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

