// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 3.25.5
package br.com.fiaprestaurante.grpc;

public interface VerificarPerfilRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fiaprestaurante.VerificarPerfilRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string publicId = 1;</code>
   * @return The publicId.
   */
  java.lang.String getPublicId();
  /**
   * <code>string publicId = 1;</code>
   * @return The bytes for publicId.
   */
  com.google.protobuf.ByteString
      getPublicIdBytes();

  /**
   * <code>string perfilRequerido = 2;</code>
   * @return The perfilRequerido.
   */
  java.lang.String getPerfilRequerido();
  /**
   * <code>string perfilRequerido = 2;</code>
   * @return The bytes for perfilRequerido.
   */
  com.google.protobuf.ByteString
      getPerfilRequeridoBytes();
}
