spring.application.name=usuario-autenticacao
server.port=8080

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.http.path=/graphql

# JWT — chave pública para validar tokens (me query)
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/publicKey.pem
# Chave privada para assinar tokens (login mutation)
app.jwt.private-key-location=classpath:keys/privateKey.pem

# gRPC server
grpc.server.port=9000

# Banco de dados MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/fiap-restaurante?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:bilzao90}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Spring DevTools — hot reload ao detectar mudanças no classpath
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
